server:
  port: 8086
spring:
  application:
    name: "solicitudes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8086"

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
  show-actuator: true

routes:
  paths:
    application: "/api/v1/solicitud"
    applicationById: "/api/v1/solicitud/{id}"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "solicitudes"
    schema: "public"
    username: "postgres"
    password: "sasa1234"
