server:
  port: "${SERVER_PORT}"
spring:
  application:
    name: "${SPRING_APPLICATION_NAME}"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: "${H2_CONSOLE_ENABLED}"
      path: "${H2_CONSOLE_PATH}"
  profiles:
    active: "${PROFILE_ACTIVE}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS}"
springdoc:
  api-docs:
    path: "/v3/api-docs"
    enabled: true
  swagger-ui:
    path: "/swagger-ui.html"
    enabled: true
    try-it-out-enabled: true
  show-actuator: false
routes:
  paths:
    application: "/api/v1/solicitud"
    applicationById: "/api/v1/solicitud/{id}"
adapters:
  r2dbc:
    host: "${DB_HOST}"
    port: "${DB_PORT}"
    database: "${DB_NAME}"
    schema: "${DB_SCHEMA}"

adapter:
  restconsumer:
    timeout: 5000
    url: "${REST_CONSUMER_AUTENTICACION}"
  aws:
    url: "${AWS_REST_CONSUMER}"
    timeout: 5000
  sqs:
    region: "${AWS_REGION_SQS_QUEUE}"
    queueUrl: "${SQS_QUEUE_URL}"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
