server:
  port: 8088
spring:
  application:
    name: "solicitudes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8088"
springdoc:
  api-docs:
    path: "/v3/api-docs"
    enabled: true
  swagger-ui:
    path: "/swagger-ui.html"
    enabled: true
    try-it-out-enabled: true
  show-actuator: true
routes:
  paths:
    application: "/api/v1/solicitud"
    applicationById: "/api/v1/solicitud/{id}"
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "solicitudes"
    schema: "public"
    username: "postgres"
    password: "sasa1234"
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8085"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"


jwt:
  secret: "9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d99a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9"
  expiration: 3600000